### ISSUE TITLE
Preserve original charset attribute

### ISSUE THREAD

**Issue by auzeonfung** [niftylettuce/forward-email#85]
Refer to #79.
Hi, 
[Delete _content-type_ headers](https://github.com/niftylettuce/forward-email/blob/master/index.js#L356) will cause non-latin character encoding error if the original email doesn't encode in utf-8.
Preserve original charset attribute may fix this issue.

**Comment by niftylettuce** [comment]
@auzeonfung I've just deployed the fix, thank you.

**Comment by niftylettuce** [comment]
@auzeonfung Deploy should finish shortly.  Can you please test soon?

**Comment by auzeonfung** [comment]
@niftylettuce Hi! 
Thank you for your reply.

I tested and the problem still exists.
![image](https://user-images.githubusercontent.com/3320227/52554097-1a392400-2e29-11e9-8c61-f5b6f39f1b22.png)

I use Outlook Mac to sent two emails with the same content and charset(iso-2022-jp).
One email was sent directly to Gmail displays without a problem, the other was sent to my own domain email forwarded by forwardemail.net is displayed incorrectly.

[https://gist.github.com/auzeonfung/5040eca3f882491b9af1461de47caafe](https://gist.github.com/auzeonfung/5040eca3f882491b9af1461de47caafe)

**Comment by niftylettuce** [comment]
I had to undo my commit that preserved original content-type and mime, as it was causing issues.  I'll need to further investigate how to fix this..

**Comment by twoshoegazer** [comment]
Hello,

Just letting you know that this is happening for me as well. Any email in Japanese coming through Forward Email is being scrambled before reaching Gmail and Apple Mail. Really hope there is a solution for this as quite a lot of my email is being affected.

**Comment by Metallion** [comment]
Has there been any news on this? I'm encountering the same issue.

When I encode an e-mail in ISO-2022-JP and send it directly to my gmail address, I get this in the header and everything works fine.

```
Content-Type: text/plain; charset=ISO-2022-JP; format=flowed; delsp=yes
```

But when I send the same mail through my custom domain doing the forward-email service, the header gets changed to UTF-8 and the text shows up as jumbled garbage.

```
Content-Type: text/plain; charset=utf-8
```

Forcing ISO-2022-JP encoding on the received e-mail in Thunderbird allows me to read it but this isn't always easy to do in other e-mail clients.

What were the issues being caused by the above fix? I would be happy to provide further information or help with the fix if I can.

**Comment by niftylettuce** [comment]
Just a heads up, I've fixed this and will be deploying the fix shortly!!!!

**Comment by Metallion** [comment]
Tested and confirmed that it works now. Thank you so much! ^_^
